export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_ANSWERS_ERROR = 'GET_ANSWERS_ERROR';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';
export const GET_NETWORK_ANSWERS_ERROR = 'GET_NETWORK_ANSWERS_ERROR';
export const GET_NETWORK_QUESTIONS_ERROR = 'GET_NETWORK_QUESTIONS_ERROR';